version: '2'

# The volume that you want to define for use int he containers.    
volumes:    
  nfs-openldap-data:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_LDAP_DATA}"
  nfs-gitlab-cfg:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_GIT_CFG}"
  nfs-gitlab-log:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_GIT_LOG}"
  nfs-gitlab-data:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_GIT_DATA}"

services:  
  openldap:
    extends:
      file: ./apps/iam/openldap/ldap.yml
      service: openldap-backup
    volumes:
    - nfs-openldap-data:/data/backup
    ports:
    - 389
    - 636

  ldap-gui:
    extends:
      file: ./apps/iam/openldap/ldap.yml
      service: ldap-user-manager
    depends_on:
    - openldap
    ports:
    - 443:443
    - 80:80
  
  git:
    extends:
      file: ./apps/git/gitlab/gitlab-ce.yml
      service: web
    depends_on:
    - openldap
    volumes:
      - nfs-gitlab-cfg:/etc/gitlab
      - nfs-gitlab-log:/var/log/gitlab
      - nfs-gitlab-data:/var/opt/gitlab
networks:
  services:
    external: FALSE
  proxy:
    external: FALSE