version: '2'

# The volume that you want to define for use int he containers.    
volumes:
  nfs-openldap-data:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_LDAP_DB}"
  nfs-gitlab-cfg:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_GIT_CFG}"
  nfs-gitlab-log:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_GIT_LOG}"
  nfs-gitlab-data:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_GIT_DATA}"
  nfs-nexus-data:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_NEXUS_DATA}"
  nfs-portainer-data:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_PORTAINER_DATA}"
  nfs-proxy-conf:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_NGINX_CONF}"
  ci-jenkins-data:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: ${_NFS_O}
      device: ":${_NFS_JENKINS_DATA}"

services:  
  openldap:
    extends:
      file: ./apps/iam/ldap.yml
      service: openldap
    volumes:
    - nfs-openldap-data:/bitnami/openldap

  ldap-gui:
    extends:
      file: ./apps/iam/ldap.yml
      service: ldap-user-manager
    depends_on:
    - openldap
  
  git:
    extends:
      file: ./apps/git/gitlab-ce.yml
      service: web
    depends_on:
    - openldap
    volumes:
    - nfs-gitlab-cfg:/etc/gitlab
    - nfs-gitlab-log:/var/log/gitlab
    - nfs-gitlab-data:/var/opt/gitlab

  nexus:
    extends:
      file: ./apps/repo/nexus-ce.yml
      service: nexus-ce
    depends_on:
    - openldap
    volumes:
    - nfs-nexus-data:/nexus-data

  portainer:
    extends:
      file: ./apps/repo/portainer.yml
      service: portainer
    depends_on:
    - openldap
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - nfs-portainer-data:/data

  proxy:
    extends:
      file: ./apps/proxy/nginx.yml
      service: nginx
    volumes:
    - nfs-proxy-conf:/etc/nginx/conf.d:rw
    ports:
    - 443:443
    - 80:80

  ci:
    extends:
      file: ./apps/ci/jenkins.yml
      service: server
    depends_on:
    - openldap
    volumes:
    - ci-jenkins-data:/var/jenkins_home:rw

# POC: Mailserver
#  mailserver-db:
#    extends:
#      file: ./apps/mailserver/postfix/postfix.yml
#      service: db
#    depends_on:
#    - openldap
#
#  mailserver:
#    extends:
#      file: ./apps/mailserver/postfix/postfix.yml
#      service: postfixadmin
#    depends_on:
#      - mailserver-db
#    ports:
#      - 8000:80
#    depends_on:
#    - mailserver-db


networks:
  services:
    external: FALSE
  proxy:
    external: FALSE
