version: '2'
services:
  openldap:
    image: docker.io/bitnami/openldap:2-debian-10
    env_file:
     - ./sample.ldap.app.env

  ldap-user-manager:
    image: wheelybird/ldap-user-manager:v1.6
    env_file:
     - ./sample.ldap.gui.env